spring.application.name=bitkart

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

spring.datasource.url=jdbc:postgresql://bitkart_user:Ute2oSHfAZvIe5NYKu0narna6kDrk9ps@dpg-d0b6gsbe5dus7380q1q0-a.oregon-postgres.render.com/bitkart
spring.datasource.username=bitkart_user
spring.datasource.password=Ute2oSHfAZvIe5NYKu0narna6kDrk9ps


spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

jwt.secret=secret
jwt.expiration=3600000
